import type * as Monaco from 'monaco-editor';

export type AppTheme = 'light' | 'cyberpunk' | 'forest' | 'midnight' | 'bubblegum' | 'peach' | 'sky' | 'lemon' | 'fire';

/** Maps app theme id to the Monaco theme name that will be registered */
export const MONACO_THEME_ID: Record<AppTheme, string> = {
  light:     'app-light',
  cyberpunk: 'app-cyberpunk',
  forest:    'app-forest',
  midnight:  'app-midnight',
  bubblegum: 'app-bubblegum',
  peach:     'app-peach',
  sky:       'app-sky',
  lemon:     'app-lemon',
  fire:      'app-fire',
};

type ThemeDef = Monaco.editor.IStandaloneThemeData;

const themes: Record<AppTheme, ThemeDef> = {
  light: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '57606a', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'cf222e' },
      { token: 'keyword.operator', foreground: 'cf222e' },
      { token: 'string', foreground: '0a3069' },
      { token: 'number', foreground: '0550ae' },
      { token: 'type', foreground: '953800' },
      { token: 'type.identifier', foreground: '953800' },
      { token: 'function', foreground: '6639ba' },
      { token: 'variable', foreground: '24292f' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#24292f',
      'editorCursor.foreground': '#0969da',
      'editor.lineHighlightBackground': '#f6f8fa',
      'editorLineNumber.foreground': '#8c959f',
      'editorLineNumber.activeForeground': '#57606a',
      'editor.selectionBackground': '#bbdefb',
      'editor.inactiveSelectionBackground': '#e8f0fe',
      'editorIndentGuide.background1': '#e7ebf0',
      'editorIndentGuide.activeBackground1': '#c8d1da',
      'editorBracketMatch.background': '#dbeafe',
      'editorBracketMatch.border': '#0969da',
    },
  },

  cyberpunk: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6040a0', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ff00cc' },
      { token: 'keyword.operator', foreground: 'ff00cc' },
      { token: 'string', foreground: '00ffcc' },
      { token: 'number', foreground: 'ffff00' },
      { token: 'type', foreground: 'ff80ff' },
      { token: 'type.identifier', foreground: 'ff80ff' },
      { token: 'function', foreground: '80ffff' },
      { token: 'variable', foreground: 'f0f0c0' },
    ],
    colors: {
      'editor.background': '#0a0313',
      'editor.foreground': '#f0f0c0',
      'editorCursor.foreground': '#ffff00',
      'editor.lineHighlightBackground': '#150825',
      'editorLineNumber.foreground': '#4a2070',
      'editorLineNumber.activeForeground': '#9040e0',
      'editor.selectionBackground': '#3a0868',
      'editor.inactiveSelectionBackground': '#220540',
      'editorIndentGuide.background1': '#1e0840',
      'editorIndentGuide.activeBackground1': '#3a1268',
      'editorBracketMatch.background': '#300868',
      'editorBracketMatch.border': '#ff00cc',
    },
  },

  forest: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '3a6040', fontStyle: 'italic' },
      { token: 'keyword', foreground: '4cbe70' },
      { token: 'keyword.operator', foreground: '4cbe70' },
      { token: 'string', foreground: 'a8d890' },
      { token: 'number', foreground: 'e0d060' },
      { token: 'type', foreground: '78d0a0' },
      { token: 'type.identifier', foreground: '78d0a0' },
      { token: 'function', foreground: '90c8a8' },
      { token: 'variable', foreground: 'd0e8d0' },
    ],
    colors: {
      'editor.background': '#061409',
      'editor.foreground': '#d0e8d0',
      'editorCursor.foreground': '#2ab56b',
      'editor.lineHighlightBackground': '#0c2010',
      'editorLineNumber.foreground': '#204830',
      'editorLineNumber.activeForeground': '#408050',
      'editor.selectionBackground': '#1a4828',
      'editor.inactiveSelectionBackground': '#102a18',
      'editorIndentGuide.background1': '#102018',
      'editorIndentGuide.activeBackground1': '#1e3828',
      'editorBracketMatch.background': '#163825',
      'editorBracketMatch.border': '#2ab56b',
    },
  },

  midnight: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '3a4070', fontStyle: 'italic' },
      { token: 'keyword', foreground: '9080f0' },
      { token: 'keyword.operator', foreground: '9080f0' },
      { token: 'string', foreground: '6ab4e8' },
      { token: 'number', foreground: 'e8d060' },
      { token: 'type', foreground: 'a898f8' },
      { token: 'type.identifier', foreground: 'a898f8' },
      { token: 'function', foreground: '80a8e8' },
      { token: 'variable', foreground: 'c8d0e8' },
    ],
    colors: {
      'editor.background': '#04091a',
      'editor.foreground': '#c8d0e8',
      'editorCursor.foreground': '#7c66e6',
      'editor.lineHighlightBackground': '#0a1030',
      'editorLineNumber.foreground': '#202848',
      'editorLineNumber.activeForeground': '#4050a0',
      'editor.selectionBackground': '#1e2c60',
      'editor.inactiveSelectionBackground': '#101a40',
      'editorIndentGuide.background1': '#101830',
      'editorIndentGuide.activeBackground1': '#202848',
      'editorBracketMatch.background': '#182050',
      'editorBracketMatch.border': '#7c66e6',
    },
  },

  bubblegum: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: 'b888a0', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c02860' },
      { token: 'keyword.operator', foreground: 'c02860' },
      { token: 'string', foreground: '903060' },
      { token: 'number', foreground: '9040b0' },
      { token: 'type', foreground: 'c03870' },
      { token: 'type.identifier', foreground: 'c03870' },
      { token: 'function', foreground: '8830a8' },
      { token: 'variable', foreground: '3d1a25' },
    ],
    colors: {
      'editor.background': '#fff0f5',
      'editor.foreground': '#3d1a25',
      'editorCursor.foreground': '#e0436e',
      'editor.lineHighlightBackground': '#fde0ea',
      'editorLineNumber.foreground': '#e8a8c0',
      'editorLineNumber.activeForeground': '#cc4878',
      'editor.selectionBackground': '#f8c0d8',
      'editor.inactiveSelectionBackground': '#fcd8e8',
      'editorIndentGuide.background1': '#f8d0e4',
      'editorIndentGuide.activeBackground1': '#f0b0cc',
      'editorBracketMatch.background': '#f5c0d5',
      'editorBracketMatch.border': '#e0436e',
    },
  },

  peach: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: 'c09070', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c04810' },
      { token: 'keyword.operator', foreground: 'c04810' },
      { token: 'string', foreground: '906020' },
      { token: 'number', foreground: '8030a0' },
      { token: 'type', foreground: 'b03820' },
      { token: 'type.identifier', foreground: 'b03820' },
      { token: 'function', foreground: '7848b0' },
      { token: 'variable', foreground: '3d2010' },
    ],
    colors: {
      'editor.background': '#fff8f0',
      'editor.foreground': '#3d2010',
      'editorCursor.foreground': '#e87030',
      'editor.lineHighlightBackground': '#fdeee0',
      'editorLineNumber.foreground': '#e8c0a0',
      'editorLineNumber.activeForeground': '#cc6830',
      'editor.selectionBackground': '#f8d8b8',
      'editor.inactiveSelectionBackground': '#fce8d0',
      'editorIndentGuide.background1': '#f8d8c0',
      'editorIndentGuide.activeBackground1': '#f0c0a0',
      'editorBracketMatch.background': '#f5d0b0',
      'editorBracketMatch.border': '#e87030',
    },
  },

  sky: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '7098b8', fontStyle: 'italic' },
      { token: 'keyword', foreground: '0050b8' },
      { token: 'keyword.operator', foreground: '0050b8' },
      { token: 'string', foreground: '006880' },
      { token: 'number', foreground: '7830b8' },
      { token: 'type', foreground: '0068c8' },
      { token: 'type.identifier', foreground: '0068c8' },
      { token: 'function', foreground: '0048a0' },
      { token: 'variable', foreground: '0a2040' },
    ],
    colors: {
      'editor.background': '#f0f8ff',
      'editor.foreground': '#0a2040',
      'editorCursor.foreground': '#0898e8',
      'editor.lineHighlightBackground': '#e0f2ff',
      'editorLineNumber.foreground': '#90c8e8',
      'editorLineNumber.activeForeground': '#1880cc',
      'editor.selectionBackground': '#b8ddf8',
      'editor.inactiveSelectionBackground': '#ccebff',
      'editorIndentGuide.background1': '#c8e8f8',
      'editorIndentGuide.activeBackground1': '#a8d5f0',
      'editorBracketMatch.background': '#b5d8f5',
      'editorBracketMatch.border': '#0898e8',
    },
  },

  lemon: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: 'a09040', fontStyle: 'italic' },
      { token: 'keyword', foreground: '806000' },
      { token: 'keyword.operator', foreground: '806000' },
      { token: 'string', foreground: '507010' },
      { token: 'number', foreground: '9030a0' },
      { token: 'type', foreground: '886800' },
      { token: 'type.identifier', foreground: '886800' },
      { token: 'function', foreground: '406810' },
      { token: 'variable', foreground: '303008' },
    ],
    colors: {
      'editor.background': '#fffeee',
      'editor.foreground': '#303008',
      'editorCursor.foreground': '#c8a000',
      'editor.lineHighlightBackground': '#fafad0',
      'editorLineNumber.foreground': '#c8c060',
      'editorLineNumber.activeForeground': '#a89000',
      'editor.selectionBackground': '#ede890',
      'editor.inactiveSelectionBackground': '#f5f0b0',
      'editorIndentGuide.background1': '#f0ec98',
      'editorIndentGuide.activeBackground1': '#e0d868',
      'editorBracketMatch.background': '#ece880',
      'editorBracketMatch.border': '#c8a000',
    },
  },

  fire: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment',           foreground: '6b2a10', fontStyle: 'italic' },
      { token: 'keyword',           foreground: 'ff6a00' },
      { token: 'keyword.operator',  foreground: 'ff6a00' },
      { token: 'string',            foreground: 'e8a040' },
      { token: 'number',            foreground: 'ffcc44' },
      { token: 'type',              foreground: 'ff8c40' },
      { token: 'type.identifier',   foreground: 'ff8c40' },
      { token: 'function',          foreground: 'ff9955' },
      { token: 'variable',          foreground: 'f0d0b0' },
    ],
    colors: {
      'editor.background':                '#0a0402',
      'editor.foreground':                '#f0d0b0',
      'editorCursor.foreground':          '#ff6a00',
      'editor.lineHighlightBackground':   '#1a0a04',
      'editorLineNumber.foreground':      '#5a2010',
      'editorLineNumber.activeForeground':'#c04010',
      'editor.selectionBackground':       '#6b2a0880',
      'editor.inactiveSelectionBackground':'#3d150440',
      'editorIndentGuide.background1':    '#2a0e06',
      'editorIndentGuide.activeBackground1':'#5a2010',
      'editorBracketMatch.background':    '#6b250880',
      'editorBracketMatch.border':        '#ff6a00',
    },
  },
};

export function registerMonacoThemes(monaco: typeof Monaco) {
  for (const [appTheme, themeId] of Object.entries(MONACO_THEME_ID)) {
    monaco.editor.defineTheme(themeId, themes[appTheme as AppTheme]);
  }
}
