import type * as Monaco from 'monaco-editor';

export type AppTheme = 'dark' | 'light' | 'ocean' | 'sunset' | 'cyberpunk' | 'forest' | 'midnight' | 'rose' | 'solar' | 'mint' | 'bubblegum' | 'lavender' | 'peach' | 'sky' | 'lemon';

/** Maps app theme id to the Monaco theme name that will be registered */
export const MONACO_THEME_ID: Record<AppTheme, string> = {
  dark:      'app-dark',
  light:     'app-light',
  ocean:     'app-ocean',
  sunset:    'app-sunset',
  cyberpunk: 'app-cyberpunk',
  forest:    'app-forest',
  midnight:  'app-midnight',
  rose:      'app-rose',
  solar:     'app-solar',
  mint:      'app-mint',
  bubblegum: 'app-bubblegum',
  lavender:  'app-lavender',
  peach:     'app-peach',
  sky:       'app-sky',
  lemon:     'app-lemon',
};

type ThemeDef = Monaco.editor.IStandaloneThemeData;

const themes: Record<AppTheme, ThemeDef> = {
  dark: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6e7681', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ff7b72' },
      { token: 'keyword.operator', foreground: 'ff7b72' },
      { token: 'string', foreground: 'a5d6ff' },
      { token: 'number', foreground: 'f2cc60' },
      { token: 'type', foreground: 'ffa657' },
      { token: 'type.identifier', foreground: 'ffa657' },
      { token: 'function', foreground: 'd2a8ff' },
      { token: 'variable', foreground: 'e6edf3' },
    ],
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#e6edf3',
      'editorCursor.foreground': '#58a6ff',
      'editor.lineHighlightBackground': '#161b22',
      'editorLineNumber.foreground': '#484f58',
      'editorLineNumber.activeForeground': '#8b949e',
      'editor.selectionBackground': '#264f78',
      'editor.inactiveSelectionBackground': '#1f3148',
      'editorIndentGuide.background1': '#21262d',
      'editorIndentGuide.activeBackground1': '#30363d',
      'editorBracketMatch.background': '#1f3148',
      'editorBracketMatch.border': '#58a6ff',
    },
  },

  light: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '57606a', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'cf222e' },
      { token: 'keyword.operator', foreground: 'cf222e' },
      { token: 'string', foreground: '0a3069' },
      { token: 'number', foreground: '0550ae' },
      { token: 'type', foreground: '953800' },
      { token: 'type.identifier', foreground: '953800' },
      { token: 'function', foreground: '6639ba' },
      { token: 'variable', foreground: '24292f' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#24292f',
      'editorCursor.foreground': '#0969da',
      'editor.lineHighlightBackground': '#f6f8fa',
      'editorLineNumber.foreground': '#8c959f',
      'editorLineNumber.activeForeground': '#57606a',
      'editor.selectionBackground': '#bbdefb',
      'editor.inactiveSelectionBackground': '#e8f0fe',
      'editorIndentGuide.background1': '#e7ebf0',
      'editorIndentGuide.activeBackground1': '#c8d1da',
      'editorBracketMatch.background': '#dbeafe',
      'editorBracketMatch.border': '#0969da',
    },
  },

  ocean: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '4a6880', fontStyle: 'italic' },
      { token: 'keyword', foreground: '5bc8ef' },
      { token: 'keyword.operator', foreground: '5bc8ef' },
      { token: 'string', foreground: '7ecba8' },
      { token: 'number', foreground: 'f0c060' },
      { token: 'type', foreground: '88d8e8' },
      { token: 'type.identifier', foreground: '88d8e8' },
      { token: 'function', foreground: '82b4e0' },
      { token: 'variable', foreground: 'c5d5e8' },
    ],
    colors: {
      'editor.background': '#040d1f',
      'editor.foreground': '#c5d5e8',
      'editorCursor.foreground': '#0bbce6',
      'editor.lineHighlightBackground': '#0a1830',
      'editorLineNumber.foreground': '#284060',
      'editorLineNumber.activeForeground': '#4a80b0',
      'editor.selectionBackground': '#1a3554',
      'editor.inactiveSelectionBackground': '#0e2238',
      'editorIndentGuide.background1': '#0f1e35',
      'editorIndentGuide.activeBackground1': '#1c3050',
      'editorBracketMatch.background': '#0e2438',
      'editorBracketMatch.border': '#0bbce6',
    },
  },

  sunset: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '7a4858', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ff7050' },
      { token: 'keyword.operator', foreground: 'ff9060' },
      { token: 'string', foreground: 'ffc07a' },
      { token: 'number', foreground: 'ffe080' },
      { token: 'type', foreground: 'ff9070' },
      { token: 'type.identifier', foreground: 'ff9070' },
      { token: 'function', foreground: 'f0b080' },
      { token: 'variable', foreground: 'faf0e8' },
    ],
    colors: {
      'editor.background': '#200f17',
      'editor.foreground': '#faf0e8',
      'editorCursor.foreground': '#ff6633',
      'editor.lineHighlightBackground': '#2e1520',
      'editorLineNumber.foreground': '#5a2838',
      'editorLineNumber.activeForeground': '#a05060',
      'editor.selectionBackground': '#5a2030',
      'editor.inactiveSelectionBackground': '#3a1520',
      'editorIndentGuide.background1': '#2e1520',
      'editorIndentGuide.activeBackground1': '#4a2030',
      'editorBracketMatch.background': '#4a2030',
      'editorBracketMatch.border': '#ff6633',
    },
  },

  cyberpunk: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6040a0', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ff00cc' },
      { token: 'keyword.operator', foreground: 'ff00cc' },
      { token: 'string', foreground: '00ffcc' },
      { token: 'number', foreground: 'ffff00' },
      { token: 'type', foreground: 'ff80ff' },
      { token: 'type.identifier', foreground: 'ff80ff' },
      { token: 'function', foreground: '80ffff' },
      { token: 'variable', foreground: 'f0f0c0' },
    ],
    colors: {
      'editor.background': '#0a0313',
      'editor.foreground': '#f0f0c0',
      'editorCursor.foreground': '#ffff00',
      'editor.lineHighlightBackground': '#150825',
      'editorLineNumber.foreground': '#4a2070',
      'editorLineNumber.activeForeground': '#9040e0',
      'editor.selectionBackground': '#3a0868',
      'editor.inactiveSelectionBackground': '#220540',
      'editorIndentGuide.background1': '#1e0840',
      'editorIndentGuide.activeBackground1': '#3a1268',
      'editorBracketMatch.background': '#300868',
      'editorBracketMatch.border': '#ff00cc',
    },
  },

  forest: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '3a6040', fontStyle: 'italic' },
      { token: 'keyword', foreground: '4cbe70' },
      { token: 'keyword.operator', foreground: '4cbe70' },
      { token: 'string', foreground: 'a8d890' },
      { token: 'number', foreground: 'e0d060' },
      { token: 'type', foreground: '78d0a0' },
      { token: 'type.identifier', foreground: '78d0a0' },
      { token: 'function', foreground: '90c8a8' },
      { token: 'variable', foreground: 'd0e8d0' },
    ],
    colors: {
      'editor.background': '#061409',
      'editor.foreground': '#d0e8d0',
      'editorCursor.foreground': '#2ab56b',
      'editor.lineHighlightBackground': '#0c2010',
      'editorLineNumber.foreground': '#204830',
      'editorLineNumber.activeForeground': '#408050',
      'editor.selectionBackground': '#1a4828',
      'editor.inactiveSelectionBackground': '#102a18',
      'editorIndentGuide.background1': '#102018',
      'editorIndentGuide.activeBackground1': '#1e3828',
      'editorBracketMatch.background': '#163825',
      'editorBracketMatch.border': '#2ab56b',
    },
  },

  midnight: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '3a4070', fontStyle: 'italic' },
      { token: 'keyword', foreground: '9080f0' },
      { token: 'keyword.operator', foreground: '9080f0' },
      { token: 'string', foreground: '6ab4e8' },
      { token: 'number', foreground: 'e8d060' },
      { token: 'type', foreground: 'a898f8' },
      { token: 'type.identifier', foreground: 'a898f8' },
      { token: 'function', foreground: '80a8e8' },
      { token: 'variable', foreground: 'c8d0e8' },
    ],
    colors: {
      'editor.background': '#04091a',
      'editor.foreground': '#c8d0e8',
      'editorCursor.foreground': '#7c66e6',
      'editor.lineHighlightBackground': '#0a1030',
      'editorLineNumber.foreground': '#202848',
      'editorLineNumber.activeForeground': '#4050a0',
      'editor.selectionBackground': '#1e2c60',
      'editor.inactiveSelectionBackground': '#101a40',
      'editorIndentGuide.background1': '#101830',
      'editorIndentGuide.activeBackground1': '#202848',
      'editorBracketMatch.background': '#182050',
      'editorBracketMatch.border': '#7c66e6',
    },
  },

  rose: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '603040', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'e86070' },
      { token: 'keyword.operator', foreground: 'e86070' },
      { token: 'string', foreground: 'f0a0b0' },
      { token: 'number', foreground: 'f0d080' },
      { token: 'type', foreground: 'f08090' },
      { token: 'type.identifier', foreground: 'f08090' },
      { token: 'function', foreground: 'd890a8' },
      { token: 'variable', foreground: 'f0dde0' },
    ],
    colors: {
      'editor.background': '#1a070c',
      'editor.foreground': '#f0dde0',
      'editorCursor.foreground': '#cc3355',
      'editor.lineHighlightBackground': '#280c12',
      'editorLineNumber.foreground': '#601828',
      'editorLineNumber.activeForeground': '#a04058',
      'editor.selectionBackground': '#5a1828',
      'editor.inactiveSelectionBackground': '#380c18',
      'editorIndentGuide.background1': '#281018',
      'editorIndentGuide.activeBackground1': '#401828',
      'editorBracketMatch.background': '#4a1020',
      'editorBracketMatch.border': '#cc3355',
    },
  },

  solar: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '806040', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ffb030' },
      { token: 'keyword.operator', foreground: 'ffb030' },
      { token: 'string', foreground: 'd4c880' },
      { token: 'number', foreground: 'ffe060' },
      { token: 'type', foreground: 'f0c050' },
      { token: 'type.identifier', foreground: 'f0c050' },
      { token: 'function', foreground: 'e0a848' },
      { token: 'variable', foreground: 'f2eed8' },
    ],
    colors: {
      'editor.background': '#1f1507',
      'editor.foreground': '#f2eed8',
      'editorCursor.foreground': '#e8a020',
      'editor.lineHighlightBackground': '#2e2008',
      'editorLineNumber.foreground': '#604818',
      'editorLineNumber.activeForeground': '#a07828',
      'editor.selectionBackground': '#5a3e10',
      'editor.inactiveSelectionBackground': '#382808',
      'editorIndentGuide.background1': '#2e2008',
      'editorIndentGuide.activeBackground1': '#4a3010',
      'editorBracketMatch.background': '#4a3208',
      'editorBracketMatch.border': '#e8a020',
    },
  },

  mint: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6aaa88', fontStyle: 'italic' },
      { token: 'keyword', foreground: '1a8a50' },
      { token: 'keyword.operator', foreground: '1a8a50' },
      { token: 'string', foreground: '2a7a60' },
      { token: 'number', foreground: 'b87800' },
      { token: 'type', foreground: '0a7a6a' },
      { token: 'type.identifier', foreground: '0a7a6a' },
      { token: 'function', foreground: '1a6890' },
      { token: 'variable', foreground: '1a3d2b' },
    ],
    colors: {
      'editor.background': '#f0faf4',
      'editor.foreground': '#1a3d2b',
      'editorCursor.foreground': '#1aad5c',
      'editor.lineHighlightBackground': '#e0f5e8',
      'editorLineNumber.foreground': '#88c8a0',
      'editorLineNumber.activeForeground': '#2a9058',
      'editor.selectionBackground': '#b8e8cc',
      'editor.inactiveSelectionBackground': '#cff0de',
      'editorIndentGuide.background1': '#d0eed8',
      'editorIndentGuide.activeBackground1': '#a8dab8',
      'editorBracketMatch.background': '#b0e0c8',
      'editorBracketMatch.border': '#1aad5c',
    },
  },

  bubblegum: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: 'b888a0', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c02860' },
      { token: 'keyword.operator', foreground: 'c02860' },
      { token: 'string', foreground: '903060' },
      { token: 'number', foreground: '9040b0' },
      { token: 'type', foreground: 'c03870' },
      { token: 'type.identifier', foreground: 'c03870' },
      { token: 'function', foreground: '8830a8' },
      { token: 'variable', foreground: '3d1a25' },
    ],
    colors: {
      'editor.background': '#fff0f5',
      'editor.foreground': '#3d1a25',
      'editorCursor.foreground': '#e0436e',
      'editor.lineHighlightBackground': '#fde0ea',
      'editorLineNumber.foreground': '#e8a8c0',
      'editorLineNumber.activeForeground': '#cc4878',
      'editor.selectionBackground': '#f8c0d8',
      'editor.inactiveSelectionBackground': '#fcd8e8',
      'editorIndentGuide.background1': '#f8d0e4',
      'editorIndentGuide.activeBackground1': '#f0b0cc',
      'editorBracketMatch.background': '#f5c0d5',
      'editorBracketMatch.border': '#e0436e',
    },
  },

  lavender: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: 'a090c8', fontStyle: 'italic' },
      { token: 'keyword', foreground: '6830c8' },
      { token: 'keyword.operator', foreground: '6830c8' },
      { token: 'string', foreground: '4848b8' },
      { token: 'number', foreground: 'b03080' },
      { token: 'type', foreground: '7840d8' },
      { token: 'type.identifier', foreground: '7840d8' },
      { token: 'function', foreground: '3858b8' },
      { token: 'variable', foreground: '2a1a40' },
    ],
    colors: {
      'editor.background': '#f5f0ff',
      'editor.foreground': '#2a1a40',
      'editorCursor.foreground': '#8055e8',
      'editor.lineHighlightBackground': '#ede5ff',
      'editorLineNumber.foreground': '#c0a8e8',
      'editorLineNumber.activeForeground': '#7848cc',
      'editor.selectionBackground': '#dac8f8',
      'editor.inactiveSelectionBackground': '#e8d8fc',
      'editorIndentGuide.background1': '#e4d8f8',
      'editorIndentGuide.activeBackground1': '#cdb8f0',
      'editorBracketMatch.background': '#d8c5f5',
      'editorBracketMatch.border': '#8055e8',
    },
  },

  peach: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: 'c09070', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c04810' },
      { token: 'keyword.operator', foreground: 'c04810' },
      { token: 'string', foreground: '906020' },
      { token: 'number', foreground: '8030a0' },
      { token: 'type', foreground: 'b03820' },
      { token: 'type.identifier', foreground: 'b03820' },
      { token: 'function', foreground: '7848b0' },
      { token: 'variable', foreground: '3d2010' },
    ],
    colors: {
      'editor.background': '#fff8f0',
      'editor.foreground': '#3d2010',
      'editorCursor.foreground': '#e87030',
      'editor.lineHighlightBackground': '#fdeee0',
      'editorLineNumber.foreground': '#e8c0a0',
      'editorLineNumber.activeForeground': '#cc6830',
      'editor.selectionBackground': '#f8d8b8',
      'editor.inactiveSelectionBackground': '#fce8d0',
      'editorIndentGuide.background1': '#f8d8c0',
      'editorIndentGuide.activeBackground1': '#f0c0a0',
      'editorBracketMatch.background': '#f5d0b0',
      'editorBracketMatch.border': '#e87030',
    },
  },

  sky: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '7098b8', fontStyle: 'italic' },
      { token: 'keyword', foreground: '0050b8' },
      { token: 'keyword.operator', foreground: '0050b8' },
      { token: 'string', foreground: '006880' },
      { token: 'number', foreground: '7830b8' },
      { token: 'type', foreground: '0068c8' },
      { token: 'type.identifier', foreground: '0068c8' },
      { token: 'function', foreground: '0048a0' },
      { token: 'variable', foreground: '0a2040' },
    ],
    colors: {
      'editor.background': '#f0f8ff',
      'editor.foreground': '#0a2040',
      'editorCursor.foreground': '#0898e8',
      'editor.lineHighlightBackground': '#e0f2ff',
      'editorLineNumber.foreground': '#90c8e8',
      'editorLineNumber.activeForeground': '#1880cc',
      'editor.selectionBackground': '#b8ddf8',
      'editor.inactiveSelectionBackground': '#ccebff',
      'editorIndentGuide.background1': '#c8e8f8',
      'editorIndentGuide.activeBackground1': '#a8d5f0',
      'editorBracketMatch.background': '#b5d8f5',
      'editorBracketMatch.border': '#0898e8',
    },
  },

  lemon: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: 'a09040', fontStyle: 'italic' },
      { token: 'keyword', foreground: '806000' },
      { token: 'keyword.operator', foreground: '806000' },
      { token: 'string', foreground: '507010' },
      { token: 'number', foreground: '9030a0' },
      { token: 'type', foreground: '886800' },
      { token: 'type.identifier', foreground: '886800' },
      { token: 'function', foreground: '406810' },
      { token: 'variable', foreground: '303008' },
    ],
    colors: {
      'editor.background': '#fffeee',
      'editor.foreground': '#303008',
      'editorCursor.foreground': '#c8a000',
      'editor.lineHighlightBackground': '#fafad0',
      'editorLineNumber.foreground': '#c8c060',
      'editorLineNumber.activeForeground': '#a89000',
      'editor.selectionBackground': '#ede890',
      'editor.inactiveSelectionBackground': '#f5f0b0',
      'editorIndentGuide.background1': '#f0ec98',
      'editorIndentGuide.activeBackground1': '#e0d868',
      'editorBracketMatch.background': '#ece880',
      'editorBracketMatch.border': '#c8a000',
    },
  },
};

export function registerMonacoThemes(monaco: typeof Monaco) {
  for (const [appTheme, themeId] of Object.entries(MONACO_THEME_ID)) {
    monaco.editor.defineTheme(themeId, themes[appTheme as AppTheme]);
  }
}
