import type { MethodDefinition } from '@/types/editor';

/**
 * STL method definitions for autocomplete
 * Maps container types to their available methods
 */
export const STL_DEFINITIONS: Record<string, MethodDefinition[]> = {
  vector: [
    {
      label: 'push_back',
      snippet: 'push_back(${1:value})',
      signature: 'void push_back(const T& value)',
      documentation: 'Adds an element to the end of the vector',
      kind: 'Method',
    },
    {
      label: 'pop_back',
      snippet: 'pop_back()',
      signature: 'void pop_back()',
      documentation: 'Removes the last element from the vector',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the vector',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the vector is empty',
      kind: 'Method',
    },
    {
      label: 'clear',
      snippet: 'clear()',
      signature: 'void clear()',
      documentation: 'Removes all elements from the vector',
      kind: 'Method',
    },
    {
      label: 'front',
      snippet: 'front()',
      signature: 'T& front()',
      documentation: 'Returns a reference to the first element',
      kind: 'Method',
    },
    {
      label: 'back',
      snippet: 'back()',
      signature: 'T& back()',
      documentation: 'Returns a reference to the last element',
      kind: 'Method',
    },
    {
      label: 'begin',
      snippet: 'begin()',
      signature: 'iterator begin()',
      documentation: 'Returns an iterator to the beginning',
      kind: 'Method',
    },
    {
      label: 'end',
      snippet: 'end()',
      signature: 'iterator end()',
      documentation: 'Returns an iterator to the end',
      kind: 'Method',
    },
    {
      label: 'insert',
      snippet: 'insert(${1:pos}, ${2:value})',
      signature: 'iterator insert(iterator pos, const T& value)',
      documentation: 'Inserts an element at the specified position',
      kind: 'Method',
    },
    {
      label: 'erase',
      snippet: 'erase(${1:pos})',
      signature: 'iterator erase(iterator pos)',
      documentation: 'Erases the element at the specified position',
      kind: 'Method',
    },
    {
      label: 'resize',
      snippet: 'resize(${1:size})',
      signature: 'void resize(size_t size)',
      documentation: 'Resizes the vector to contain size elements',
      kind: 'Method',
    },
  ],

  map: [
    {
      label: 'insert',
      snippet: 'insert({${1:key}, ${2:value}})',
      signature: 'pair<iterator, bool> insert(const value_type& val)',
      documentation: 'Inserts a key-value pair into the map',
      kind: 'Method',
    },
    {
      label: 'erase',
      snippet: 'erase(${1:key})',
      signature: 'size_t erase(const key_type& key)',
      documentation: 'Erases the element with the given key',
      kind: 'Method',
    },
    {
      label: 'find',
      snippet: 'find(${1:key})',
      signature: 'iterator find(const key_type& key)',
      documentation: 'Finds an element with the given key',
      kind: 'Method',
    },
    {
      label: 'count',
      snippet: 'count(${1:key})',
      signature: 'size_t count(const key_type& key) const',
      documentation: 'Returns the number of elements with the given key (0 or 1)',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the map',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the map is empty',
      kind: 'Method',
    },
    {
      label: 'clear',
      snippet: 'clear()',
      signature: 'void clear()',
      documentation: 'Removes all elements from the map',
      kind: 'Method',
    },
    {
      label: 'begin',
      snippet: 'begin()',
      signature: 'iterator begin()',
      documentation: 'Returns an iterator to the beginning',
      kind: 'Method',
    },
    {
      label: 'end',
      snippet: 'end()',
      signature: 'iterator end()',
      documentation: 'Returns an iterator to the end',
      kind: 'Method',
    },
  ],

  unordered_map: [
    {
      label: 'insert',
      snippet: 'insert({${1:key}, ${2:value}})',
      signature: 'pair<iterator, bool> insert(const value_type& val)',
      documentation: 'Inserts a key-value pair into the unordered map',
      kind: 'Method',
    },
    {
      label: 'erase',
      snippet: 'erase(${1:key})',
      signature: 'size_t erase(const key_type& key)',
      documentation: 'Erases the element with the given key',
      kind: 'Method',
    },
    {
      label: 'find',
      snippet: 'find(${1:key})',
      signature: 'iterator find(const key_type& key)',
      documentation: 'Finds an element with the given key',
      kind: 'Method',
    },
    {
      label: 'count',
      snippet: 'count(${1:key})',
      signature: 'size_t count(const key_type& key) const',
      documentation: 'Returns the number of elements with the given key (0 or 1)',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the unordered map',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the unordered map is empty',
      kind: 'Method',
    },
    {
      label: 'clear',
      snippet: 'clear()',
      signature: 'void clear()',
      documentation: 'Removes all elements from the unordered map',
      kind: 'Method',
    },
  ],

  set: [
    {
      label: 'insert',
      snippet: 'insert(${1:value})',
      signature: 'pair<iterator, bool> insert(const value_type& val)',
      documentation: 'Inserts an element into the set',
      kind: 'Method',
    },
    {
      label: 'erase',
      snippet: 'erase(${1:value})',
      signature: 'size_t erase(const value_type& val)',
      documentation: 'Erases the element with the given value',
      kind: 'Method',
    },
    {
      label: 'find',
      snippet: 'find(${1:value})',
      signature: 'iterator find(const value_type& val)',
      documentation: 'Finds an element with the given value',
      kind: 'Method',
    },
    {
      label: 'count',
      snippet: 'count(${1:value})',
      signature: 'size_t count(const value_type& val) const',
      documentation: 'Returns the number of elements with the given value (0 or 1)',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the set',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the set is empty',
      kind: 'Method',
    },
    {
      label: 'clear',
      snippet: 'clear()',
      signature: 'void clear()',
      documentation: 'Removes all elements from the set',
      kind: 'Method',
    },
    {
      label: 'begin',
      snippet: 'begin()',
      signature: 'iterator begin()',
      documentation: 'Returns an iterator to the beginning',
      kind: 'Method',
    },
    {
      label: 'end',
      snippet: 'end()',
      signature: 'iterator end()',
      documentation: 'Returns an iterator to the end',
      kind: 'Method',
    },
  ],

  unordered_set: [
    {
      label: 'insert',
      snippet: 'insert(${1:value})',
      signature: 'pair<iterator, bool> insert(const value_type& val)',
      documentation: 'Inserts an element into the unordered set',
      kind: 'Method',
    },
    {
      label: 'erase',
      snippet: 'erase(${1:value})',
      signature: 'size_t erase(const value_type& val)',
      documentation: 'Erases the element with the given value',
      kind: 'Method',
    },
    {
      label: 'find',
      snippet: 'find(${1:value})',
      signature: 'iterator find(const value_type& val)',
      documentation: 'Finds an element with the given value',
      kind: 'Method',
    },
    {
      label: 'count',
      snippet: 'count(${1:value})',
      signature: 'size_t count(const value_type& val) const',
      documentation: 'Returns the number of elements with the given value (0 or 1)',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the unordered set',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the unordered set is empty',
      kind: 'Method',
    },
    {
      label: 'clear',
      snippet: 'clear()',
      signature: 'void clear()',
      documentation: 'Removes all elements from the unordered set',
      kind: 'Method',
    },
  ],

  stack: [
    {
      label: 'push',
      snippet: 'push(${1:value})',
      signature: 'void push(const T& value)',
      documentation: 'Pushes an element onto the top of the stack',
      kind: 'Method',
    },
    {
      label: 'pop',
      snippet: 'pop()',
      signature: 'void pop()',
      documentation: 'Removes the top element from the stack',
      kind: 'Method',
    },
    {
      label: 'top',
      snippet: 'top()',
      signature: 'T& top()',
      documentation: 'Returns a reference to the top element',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the stack',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the stack is empty',
      kind: 'Method',
    },
  ],

  queue: [
    {
      label: 'push',
      snippet: 'push(${1:value})',
      signature: 'void push(const T& value)',
      documentation: 'Adds an element to the back of the queue',
      kind: 'Method',
    },
    {
      label: 'pop',
      snippet: 'pop()',
      signature: 'void pop()',
      documentation: 'Removes the front element from the queue',
      kind: 'Method',
    },
    {
      label: 'front',
      snippet: 'front()',
      signature: 'T& front()',
      documentation: 'Returns a reference to the front element',
      kind: 'Method',
    },
    {
      label: 'back',
      snippet: 'back()',
      signature: 'T& back()',
      documentation: 'Returns a reference to the back element',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the queue',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the queue is empty',
      kind: 'Method',
    },
  ],

  priority_queue: [
    {
      label: 'push',
      snippet: 'push(${1:value})',
      signature: 'void push(const T& value)',
      documentation: 'Adds an element to the priority queue',
      kind: 'Method',
    },
    {
      label: 'pop',
      snippet: 'pop()',
      signature: 'void pop()',
      documentation: 'Removes the top element from the priority queue',
      kind: 'Method',
    },
    {
      label: 'top',
      snippet: 'top()',
      signature: 'const T& top() const',
      documentation: 'Returns a reference to the top element',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the priority queue',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the priority queue is empty',
      kind: 'Method',
    },
  ],

  deque: [
    {
      label: 'push_back',
      snippet: 'push_back(${1:value})',
      signature: 'void push_back(const T& value)',
      documentation: 'Adds an element to the end of the deque',
      kind: 'Method',
    },
    {
      label: 'push_front',
      snippet: 'push_front(${1:value})',
      signature: 'void push_front(const T& value)',
      documentation: 'Adds an element to the beginning of the deque',
      kind: 'Method',
    },
    {
      label: 'pop_back',
      snippet: 'pop_back()',
      signature: 'void pop_back()',
      documentation: 'Removes the last element from the deque',
      kind: 'Method',
    },
    {
      label: 'pop_front',
      snippet: 'pop_front()',
      signature: 'void pop_front()',
      documentation: 'Removes the first element from the deque',
      kind: 'Method',
    },
    {
      label: 'front',
      snippet: 'front()',
      signature: 'T& front()',
      documentation: 'Returns a reference to the first element',
      kind: 'Method',
    },
    {
      label: 'back',
      snippet: 'back()',
      signature: 'T& back()',
      documentation: 'Returns a reference to the last element',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the deque',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the deque is empty',
      kind: 'Method',
    },
  ],

  string: [
    {
      label: 'length',
      snippet: 'length()',
      signature: 'size_t length() const',
      documentation: 'Returns the length of the string',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the size of the string',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the string is empty',
      kind: 'Method',
    },
    {
      label: 'clear',
      snippet: 'clear()',
      signature: 'void clear()',
      documentation: 'Removes all characters from the string',
      kind: 'Method',
    },
    {
      label: 'substr',
      snippet: 'substr(${1:pos}, ${2:len})',
      signature: 'string substr(size_t pos, size_t len) const',
      documentation: 'Returns a substring starting at position pos with length len',
      kind: 'Method',
    },
    {
      label: 'append',
      snippet: 'append(${1:str})',
      signature: 'string& append(const string& str)',
      documentation: 'Appends a string to the end',
      kind: 'Method',
    },
    {
      label: 'push_back',
      snippet: 'push_back(${1:char})',
      signature: 'void push_back(char c)',
      documentation: 'Appends a character to the end',
      kind: 'Method',
    },
    {
      label: 'pop_back',
      snippet: 'pop_back()',
      signature: 'void pop_back()',
      documentation: 'Removes the last character',
      kind: 'Method',
    },
    {
      label: 'find',
      snippet: 'find(${1:str})',
      signature: 'size_t find(const string& str) const',
      documentation: 'Finds the first occurrence of a substring',
      kind: 'Method',
    },
    {
      label: 'rfind',
      snippet: 'rfind(${1:str})',
      signature: 'size_t rfind(const string& str) const',
      documentation: 'Finds the last occurrence of a substring',
      kind: 'Method',
    },
    {
      label: 'replace',
      snippet: 'replace(${1:pos}, ${2:len}, ${3:str})',
      signature: 'string& replace(size_t pos, size_t len, const string& str)',
      documentation: 'Replaces a portion of the string',
      kind: 'Method',
    },
    {
      label: 'insert',
      snippet: 'insert(${1:pos}, ${2:str})',
      signature: 'string& insert(size_t pos, const string& str)',
      documentation: 'Inserts a string at the specified position',
      kind: 'Method',
    },
    {
      label: 'erase',
      snippet: 'erase(${1:pos}, ${2:len})',
      signature: 'string& erase(size_t pos, size_t len)',
      documentation: 'Erases a portion of the string',
      kind: 'Method',
    },
    {
      label: 'c_str',
      snippet: 'c_str()',
      signature: 'const char* c_str() const',
      documentation: 'Returns a C-style character string',
      kind: 'Method',
    },
  ],

  list: [
    {
      label: 'push_back',
      snippet: 'push_back(${1:value})',
      signature: 'void push_back(const T& value)',
      documentation: 'Adds an element to the end of the list',
      kind: 'Method',
    },
    {
      label: 'push_front',
      snippet: 'push_front(${1:value})',
      signature: 'void push_front(const T& value)',
      documentation: 'Adds an element to the beginning of the list',
      kind: 'Method',
    },
    {
      label: 'pop_back',
      snippet: 'pop_back()',
      signature: 'void pop_back()',
      documentation: 'Removes the last element from the list',
      kind: 'Method',
    },
    {
      label: 'pop_front',
      snippet: 'pop_front()',
      signature: 'void pop_front()',
      documentation: 'Removes the first element from the list',
      kind: 'Method',
    },
    {
      label: 'size',
      snippet: 'size()',
      signature: 'size_t size() const',
      documentation: 'Returns the number of elements in the list',
      kind: 'Method',
    },
    {
      label: 'empty',
      snippet: 'empty()',
      signature: 'bool empty() const',
      documentation: 'Returns true if the list is empty',
      kind: 'Method',
    },
    {
      label: 'clear',
      snippet: 'clear()',
      signature: 'void clear()',
      documentation: 'Removes all elements from the list',
      kind: 'Method',
    },
  ],

  // LeetCode custom types
  ListNode: [
    {
      label: 'val',
      snippet: 'val',
      signature: 'int val',
      documentation: 'The value stored in the node',
      kind: 'Field',
    },
    {
      label: 'next',
      snippet: 'next',
      signature: 'ListNode* next',
      documentation: 'Pointer to the next node',
      kind: 'Field',
    },
  ],

  TreeNode: [
    {
      label: 'val',
      snippet: 'val',
      signature: 'int val',
      documentation: 'The value stored in the node',
      kind: 'Field',
    },
    {
      label: 'left',
      snippet: 'left',
      signature: 'TreeNode* left',
      documentation: 'Pointer to the left child',
      kind: 'Field',
    },
    {
      label: 'right',
      snippet: 'right',
      signature: 'TreeNode* right',
      documentation: 'Pointer to the right child',
      kind: 'Field',
    },
  ],
};
